erDiagram
    Book ||--|| Storage : "хранится как"
    Storage ||--o| FileBook : "хранится как"
    Storage ||--o| ArchiveEntry : "хранится как"
    File || --o{ ArchiveEntry : содержит
    File || --|| FileBook : содержит

    Book {
        int Id PK
        string Title
        text Anotation
    }
    
    Storage{
        int Id PK
        int BookId FK "UNIQUE"
        byte Type
        string ContentType
    }

    FileBook {
        int Id PK
        int StorageId FK "UNIQUE"
        int FileId FK "UNIQUE"
    }
    
    ArchiveEntry {
        int Id PK
        int StorageId FK "UNIQUE"
        int FileId FK "UNIQUE"
        string EntryName
        long FileSize
        long CompressedSize
    }

    File{
        int Id PK
        string FileName
        string FilePath
        long FileSize
    }