erDiagram
    Books ||--|{ Documents : "представлена"   
    Books ||--o{ BooksKeywords: ""   
    Keywords||--|{ BooksKeywords: ""
    Books ||--o{ BooksGenres : ""
    Genres ||--|{ BooksGenres : ""
    Books ||--|{ BooksAuthors  : "написана"
    Books ||--o{ Translators  : "переведена"
    Books ||--o| Anotations : "описание"
    Books ||--o| Covers : ""
    Books ||--o| BooksPublishers : "издана"
    Publishers ||--|{ BooksPublishers : "издал"

    Documents ||--o| ArchiveEntries : "размещается"
    ArchiveFiles ||--|{ ArchiveEntries : "содержит"
    Documents ||--o| BooksFiles : "размещается"
    Documents ||--o{ DocAuthors : "создан"
    
    DocAuthors ||--|| Persons : ""
    BooksAuthors ||--|| Persons : ""
    Translators ||--|| Persons : ""

    Books {
        int Id PK
        string Title
        string City
        int Year
    }

    BooksKeywords{
        int BooksId     PK, FK
        int KeywordId   PK, FK
    }

    Keywords{
        int Id PK        
        string Keyword        
    }

    Genres{
        int Id PK
        string Genre       "UK"
    }

    BooksGenres{
        int BookId  PK, FK
        int GenreId PK, FK
    }

    Documents{
        int Id PK
        int BooksId FK "UK"
        byte StorageType "UK"
        byte ContentType "UK"
    }

    Anotations{
        int BookId PK, FK
        text Anotation
    }

    BooksFiles {
        int DocumentsId PK, FK
        string FileName
        string FilePath
        long FileSize
    }
    
    ArchiveEntries {
        int DocumentsId PK, FK
        int FileId      PK, FK
        string EntryName
        long FileSize
        long CompressedSize
    }

    ArchiveFiles{
        int Id PK
        string FileName
        string FilePath
        long FileSize
    }

    BooksAuthors{
        int PersonsID PK, FK
        int BooksID   PK, FK
    }

    Translators{
        int PersonsID PK, FK
        int BooksID   PK, FK
    }

    DocAuthors{
        int PersonsID     PK, FK
        int DocumentsID   PK, FK
    }

    Persons{
        int Id PK
        string LastName
        string FirstName
        string MiddleName
        string NickName
    }

    Covers{
        int BookId PK, FK
        binary Cover
    }

     Publishers{
        int Id PK
        string Publisher "UK"
     }
     
     BooksPublishers{
        int BookId      PK, FK
        int PublisherID PK, FK
     }